### ISSUE TITLE
Change keys in demo ?

### ISSUE THREAD

**Issue by macbroadcast** [pubnub/pubnub-chat-channel-presence#1]
After i watched the codereview video a few times , i was curious , because there is no nodejs instance ,so i just need to change the key from "demo", "demo" to my actual Pubnub `publish` and `subscribe` key in the `chat.js` and i need to have "presence" and "storage" enabled in my account, correct ?
`
// READY FUNCTION
// 
// --------------------------------------------------------------------------
function ready(user) {
    hide('overlay');
    hide('twitter-login');

```
set_current_user(user);

// Setup Connection Based on User Data
// This will provide Connectivity References
p = p.init({
    publish_key   : 'demo',
    subscribe_key : 'demo',
    ssl           : false,`
```

Thanks

**Comment by stephenlb** [comment]
yup!  you are correct :-)  :+1:
